# Generated by Django 6.0.7 on 2026-07-30 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('location_name', models.CharField(default='Municipal Drain Zone 1', max_length=256)),
                ('latitude', models.FloatField(default=17.385043)),
                ('longitude', models.FloatField(default=78.486671)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='OFFLINE', max_length=16)),
                ('firmware_version', models.CharField(default='v1.0.4-esp32', max_length=32)),
                ('battery_percentage', models.FloatField(blank=True, null=True)),
                ('signal_strength_dbm', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blockage Detected')], default='INACTIVE', max_length=16)),
                ('detected_objects', models.JSONField(blank=True, default=list)),
                ('blockage_percentage', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_feeds', to='dashboard.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('alert_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_level_cm', models.FloatField(blank=True, null=True)),
                ('solid_level_cm', models.FloatField(blank=True, null=True)),
                ('gas_ppm', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('rain_detected', models.BooleanField(blank=True, default=False, null=True)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('signal_dbm', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='dashboard.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
